"""added bg_image to courses

Revision ID: 2184c47e6cfa
Revises: 82217014e183
Create Date: 2022-05-31 13:33:33.175408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2184c47e6cfa'
down_revision = '82217014e183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('background_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_courses_background_image_id_images'), 'courses', 'images', ['background_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_courses_background_image_id_images'), 'courses', type_='foreignkey')
    op.drop_column('courses', 'background_image_id')
    # ### end Alembic commands ###
